version: '3.1'

networks:
  dev_network:

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ".env"
    working_dir: /var/www/html/
    ports:
      - "8089:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - dev_network
  db:
    image: mysql:${MYSQL_VERSION:-latest}
    container_name: ${MYSQL_HOST}
    restart: always
    env_file:
      - ".env"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - dev_network
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./db_scripts:/docker-entrypoint-initdb.d

